### ISSUE TITLE
[Bug] Can't open Enderchest in Minecraft 1.14.3 due to sound error

### ISSUE THREAD

**Issue by antoinech2** [brunyman/CustomEnderChest#5]
When I open enderchest, I've this error in console:

`[10:28:19] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CustomEnderChest v1.11.1
java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.BLOCK_ENDERCHEST_OPEN
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_181]
	at org.bukkit.Sound.valueOf(Sound.java:11) ~[patched_1.14.3.jar:git-Paper-111]
	at net.craftersland.customenderchest.SoundHandler.sendEnderchestOpenSound(SoundHandler.java:49) ~[?:?]
	at net.craftersland.customenderchest.utils.EnderChestUtils.openMenu(EnderChestUtils.java:130) ~[?:?]
	at net.craftersland.customenderchest.PlayerHandler.onPlayerInteract(PlayerHandler.java:76) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor21.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.3.jar:git-Paper-111]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.3.jar:git-Paper-111]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.3.jar:git-Paper-111]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.3.jar:git-Paper-111]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:445) ~[patched_1.14.3.jar:git-Paper-111]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:441) ~[patched_1.14.3.jar:git-Paper-111]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1392) ~[patched_1.14.3.jar:git-Paper-111]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.3.jar:git-Paper-111]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.3.jar:git-Paper-111]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-111]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-111]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-111]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-111]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-111]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-111]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-111]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.3.jar:git-Paper-111]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:979) ~[patched_1.14.3.jar:git-Paper-111]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-111]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
`

Please fix it! Thanks!

**Comment by natr566** [comment]
I know this isn't a fix but you can disable sounds in the config and then it works.

**Comment by antoinech2** [comment]
Okay, thank you!
