### ISSUE TITLE
Import from FLATFILE Error

### ISSUE THREAD

**Issue by MaximeMichaud** [brunyman/CustomEnderChest#7]
`08:23:04: java.lang.IllegalArgumentException: Item cannot be null
08:23:04: at org.apache.commons.lang.Validate.noNullElements(Validate.java:364)
08:23:04: at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventory.addItem(CraftInventory.java:265)
08:23:04: at net.craftersland.customenderchest.storage.MysqlStorage.decodeInventory(MysqlStorage.java:303)
08:23:04: at net.craftersland.customenderchest.storage.MysqlStorage.loadEnderChest(MysqlStorage.java:264)
08:23:04: at net.craftersland.customenderchest.commands.FileToMysqlCmd$1.run(FileToMysqlCmd.java:76)
08:23:04: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
08:23:04: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
08:23:04: at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
08:23:04: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
08:23:04: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
08:23:04: at java.lang.Thread.run(Thread.java:748)
08:23:04: [CustomEnderChest] Failed to decode inventory for fightmaxime! Error: Length of Base64 encoded input string is not a multiple of 4.
08:23:04: java.lang.IllegalArgumentException: Length of Base64 encoded input string is not a multiple of 4.
08:23:04: at org.yaml.snakeyaml.external.biz.base64Coder.Base64Coder.decode(Base64Coder.java:267)
08:23:04: at org.yaml.snakeyaml.external.biz.base64Coder.Base64Coder.decodeLines(Base64Coder.java:218)
08:23:04: at net.craftersland.customenderchest.utils.EncodingUtil.fromBase64(EncodingUtil.java:37)
08:23:04: at net.craftersland.customenderchest.storage.MysqlStorage.decodeInventory(MysqlStorage.java:311)
08:23:04: at net.craftersland.customenderchest.storage.MysqlStorage.loadEnderChest(MysqlStorage.java:264)
08:23:04: at net.craftersland.customenderchest.commands.FileToMysqlCmd$1.run(FileToMysqlCmd.java:76)
08:23:04: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
08:23:04: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
08:23:04: at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
08:23:04: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
08:23:04: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
08:23:04: at java.lang.Thread.run(Thread.java:748)`

**Comment by MaximeMichaud** [comment]
Seem not happening with : modded-NBT-data-support: false
ProtocolLib Ver : 4.5.1
